// swift-tools-version:5.10
//
// Generated by applesdk/release/release.sh for version 30.1.3. Do not edit by hand.

import PackageDescription

let package = Package(
    name: "YBVRAppleSDK",
    platforms: [.iOS(.v17), .visionOS("26.0")],
    products: [
        .library(
            name: "YBVRAppleSDK",
            targets: [
                "YBVRAppleSDK",
                "Yams",
                "KSPlayer",
                "FFmpegKit",
                "libass",
                "Libavcodec",
                "Libavdevice",
                "Libavfilter",
                "Libavformat",
                "Libavutil",
                "Libswresample",
                "Libswscale",
            ]
        )
    ],
    targets: [
        .binaryTarget(
            name: "YBVRAppleSDK",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.3/YBVRAppleSDK.xcframework.zip",
            checksum: "0fa934a0ddfa88f16b78469496ec7707e7753e47211201a8e8fa59b6e9763cfa"
        ),
        .binaryTarget(
            name: "Yams",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.3/Yams.xcframework.zip",
            checksum: "c79ece90be485b6a2cde50e0bc580d6a29eec996ede21d3406d599c151dbfd45"
        ),
        .binaryTarget(
            name: "KSPlayer",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.3/KSPlayer.xcframework.zip",
            checksum: "518c7522ea6216586711968d17345683279575804cff6183618e619729837af6"
        ),
        .binaryTarget(
            name: "FFmpegKit",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.3/FFmpegKit.xcframework.zip",
            checksum: "64221874e8fc04d9bad960da22569c6a9f0cf99473975ee09de4e1fa02371621"
        ),
        .binaryTarget(
            name: "libass",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.3/libass.xcframework.zip",
            checksum: "637e908b5f98d7757de26b67b84481dee915cb6060e4dc2a8022bacd09195dc1"
        ),
        .binaryTarget(
            name: "Libavcodec",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.3/Libavcodec.xcframework.zip",
            checksum: "dd2df5ff412e2cc2ab225c38ee1aaf98aa2cf6af92a79b1d3ffcd6c101bcbcb4"
        ),
        .binaryTarget(
            name: "Libavdevice",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.3/Libavdevice.xcframework.zip",
            checksum: "dd1604b17e1fda642abb1483b8d5dc9a3c0fc410460c7a6c21d315e5e103c8b2"
        ),
        .binaryTarget(
            name: "Libavfilter",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.3/Libavfilter.xcframework.zip",
            checksum: "51b3625b4e9860020c7dd5fc1086b055ae906b229fbb8f5b8108163602e0ce46"
        ),
        .binaryTarget(
            name: "Libavformat",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.3/Libavformat.xcframework.zip",
            checksum: "824b0687180d1df4751dd673eaf9ba5b78724c436fdbf5bb67edee76fbabffe0"
        ),
        .binaryTarget(
            name: "Libavutil",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.3/Libavutil.xcframework.zip",
            checksum: "181880722cd0a26307d9bc32de1f306e127cf2e5cec63c2ed9b63dfacd133ff3"
        ),
        .binaryTarget(
            name: "Libswresample",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.3/Libswresample.xcframework.zip",
            checksum: "680ae763044603c5b4e8308140883565f49c203132ed140a89e7b37e7c6ddeab"
        ),
        .binaryTarget(
            name: "Libswscale",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.3/Libswscale.xcframework.zip",
            checksum: "03c61a2fe2d712827ef4e745f992737e72f0124a17e9da3f33f4e885cee0ffc8"
        ),
    ]
)
