// swift-tools-version:5.10
//
// Generated by applesdk/release/release.sh for version 30.1.4. Do not edit by hand.

import PackageDescription

let package = Package(
    name: "YBVRAppleSDK",
    platforms: [.iOS(.v17), .visionOS("26.0")],
    products: [
        .library(
            name: "YBVRAppleSDK",
            targets: [
                "YBVRAppleSDK",
                "Yams",
                "KSPlayer",
                "FFmpegKit",
                "libass",
                "Libavcodec",
                "Libavdevice",
                "Libavfilter",
                "Libavformat",
                "Libavutil",
                "Libswresample",
                "Libswscale",
            ]
        )
    ],
    targets: [
        .binaryTarget(
            name: "YBVRAppleSDK",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.4/YBVRAppleSDK.xcframework.zip",
            checksum: "cce1778a021dcd00aaabf43917aae1247113d0be7e5d2a71878fe1f3d79c145b"
        ),
        .binaryTarget(
            name: "Yams",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.4/Yams.xcframework.zip",
            checksum: "e123ba1feba42eabf8353adfb41cd031e8c62f4d113b3fa477729ed5e5208d8f"
        ),
        .binaryTarget(
            name: "KSPlayer",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.4/KSPlayer.xcframework.zip",
            checksum: "16c9458843d70d754b4ff0eab3a8f4fc4b19dcc305ff1ea6af6c206b17189431"
        ),
        .binaryTarget(
            name: "FFmpegKit",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.4/FFmpegKit.xcframework.zip",
            checksum: "f65c4127a6fe07d66ca2bd01cee807e0e29ed95b00f36a7e8d2ba3b8cc3b72bf"
        ),
        .binaryTarget(
            name: "libass",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.4/libass.xcframework.zip",
            checksum: "b335fb502649fde6fd568e7ac2a0744196456dbb1607f90e7f801df648cb4b98"
        ),
        .binaryTarget(
            name: "Libavcodec",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.4/Libavcodec.xcframework.zip",
            checksum: "b8834a77711d8d299f9c495554059452b896472b6fd49ebdf96d5fb89dd9383e"
        ),
        .binaryTarget(
            name: "Libavdevice",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.4/Libavdevice.xcframework.zip",
            checksum: "b053b92bae5874e577c6c78c71ef2666464a327b0fd97a37e1868023c73f6adb"
        ),
        .binaryTarget(
            name: "Libavfilter",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.4/Libavfilter.xcframework.zip",
            checksum: "4b1b3ce1118a26588caa99d186347f2af41b363073c4261498175d289bc353d3"
        ),
        .binaryTarget(
            name: "Libavformat",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.4/Libavformat.xcframework.zip",
            checksum: "329d44722a66923b6075a17830012f2a3b4a2af33d0dae29b992fa832fb6f652"
        ),
        .binaryTarget(
            name: "Libavutil",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.4/Libavutil.xcframework.zip",
            checksum: "89c7bb743243ab79f366de212c43b80f1d2d1ce3711dee8c0f057288b6212e40"
        ),
        .binaryTarget(
            name: "Libswresample",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.4/Libswresample.xcframework.zip",
            checksum: "16d5b5dbdf7f1f7d5420cda8f748102708f527dd3a6551962924ace2f55c18f4"
        ),
        .binaryTarget(
            name: "Libswscale",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.4/Libswscale.xcframework.zip",
            checksum: "4bcdf3a9f0fafe1816c90bcf92e1279504cc457176f904fd15a337e9fcd61e78"
        ),
    ]
)
