// swift-tools-version:5.10
//
// Generated by applesdk/release/release.sh for version 30.1.0. Do not edit by hand.

import PackageDescription

let package = Package(
    name: "YBVRAppleSDK",
    platforms: [.iOS(.v17), .visionOS("26.0")],
    products: [
        .library(
            name: "YBVRAppleSDK",
            targets: [
                "YBVRAppleSDK",
                "Yams",
                "KSPlayer",
                "FFmpegKit",
                "libass",
                "Libavcodec",
                "Libavdevice",
                "Libavfilter",
                "Libavformat",
                "Libavutil",
                "Libswresample",
                "Libswscale",
            ]
        )
    ],
    targets: [
        .binaryTarget(
            name: "YBVRAppleSDK",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.0/YBVRAppleSDK.xcframework.zip",
            checksum: "29f77b3a3f3e13b40225258fdcdc4483da01beeca894bb43b6d3134c7fb87108"
        ),
        .binaryTarget(
            name: "Yams",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.0/Yams.xcframework.zip",
            checksum: "25dfaee17d075bae4beb93af6c40fa3434471dc3b4f0563a02263259a3c84b24"
        ),
        .binaryTarget(
            name: "KSPlayer",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.0/KSPlayer.xcframework.zip",
            checksum: "c5a1940625ee7d00c48f720bac18651aa378af9e71660a8652070cd1044fe5a5"
        ),
        .binaryTarget(
            name: "FFmpegKit",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.0/FFmpegKit.xcframework.zip",
            checksum: "77eb8aaf8d0d4cadba2821fdeee4010d053fffde602e9b1ad31b479529211d38"
        ),
        .binaryTarget(
            name: "libass",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.0/libass.xcframework.zip",
            checksum: "3c981c5eccfec28f125ad89c0244de228cb023103be7b8f6b00f4b5fee6b67c1"
        ),
        .binaryTarget(
            name: "Libavcodec",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.0/Libavcodec.xcframework.zip",
            checksum: "18e395470549b661ab38069b9a70d07b0304e76df414b7428f2cb92cae3c0c59"
        ),
        .binaryTarget(
            name: "Libavdevice",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.0/Libavdevice.xcframework.zip",
            checksum: "0ed6a18baf32d6a4b828aa81e3728198bada7b32136968bc3c458224fe5442fc"
        ),
        .binaryTarget(
            name: "Libavfilter",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.0/Libavfilter.xcframework.zip",
            checksum: "76f29ec20e3c7ae0e2890a7cdb1c8cf2f193602b79e6b562d5587693ca27d965"
        ),
        .binaryTarget(
            name: "Libavformat",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.0/Libavformat.xcframework.zip",
            checksum: "55be441d237039674b29e392469d312a758f922ae54e53dc3dc46984aa8c7baf"
        ),
        .binaryTarget(
            name: "Libavutil",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.0/Libavutil.xcframework.zip",
            checksum: "6fd1fdf5a1edbb65d99c695383ea90df9bc156b84e71f5249812de960d822146"
        ),
        .binaryTarget(
            name: "Libswresample",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.0/Libswresample.xcframework.zip",
            checksum: "0d27b9be0c4d1d787690b9fe18803f183ac500a7c31cc73b68c034b57eb7f59b"
        ),
        .binaryTarget(
            name: "Libswscale",
            url: "https://github.com/YBVR360/applesdk-external/releases/download/30.1.0/Libswscale.xcframework.zip",
            checksum: "2217fbce4dd1fc0a433a8bac24f1b663360b33bf1af9df750007f9049711e53e"
        ),
    ]
)
